# Generated by Django 4.2.16 on 2026-05-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Concediu de odihna'), ('medical', 'Concediu medical'), ('unpaid', 'Concediu fara plata'), ('study', 'Concediu de studii'), ('maternity', 'Concediu maternitate / paternitate'), ('special', 'Concediu pentru evenimente speciale')], default='annual', max_length=20, verbose_name='Tip concediu')),
                ('start_date', models.DateField(verbose_name='Data inceput')),
                ('end_date', models.DateField(verbose_name='Data sfarsit')),
                ('days', models.PositiveIntegerField(default=0, help_text='Calculat automat la salvare.', verbose_name='Numar zile')),
                ('reason', models.TextField(verbose_name='Motiv')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/attachments/', verbose_name='Atasament justificativ (optional)')),
                ('status', models.CharField(choices=[('pending', 'In asteptare'), ('approved', 'Aprobata'), ('rejected', 'Respinsa')], default='pending', max_length=20, verbose_name='Status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Data deciziei')),
                ('decision_note', models.TextField(blank=True, help_text='Motivul respingerii sau orice observatii la aprobare.', verbose_name='Nota decizie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizata la')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_requests', to=settings.AUTH_USER_MODEL, verbose_name='Decis de')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Angajat')),
            ],
            options={
                'verbose_name': 'Cerere de concediu',
                'verbose_name_plural': 'Cereri de concediu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Stocata in Cloudinary in productie.', upload_to='leaves/signatures/', verbose_name='Imagine semnatura')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Semnata la')),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='leaves.leaverequest', verbose_name='Cerere')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Semnatura',
                'verbose_name_plural': 'Semnaturi',
            },
        ),
    ]
