# Generated by Django 4.2.16 on 2026-05-07 17:03

from django.db import migrations, models
import leaves.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=leaves.models._attachment_storage, upload_to='leaves/attachments/', verbose_name='Atasament justificativ (optional)'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(help_text='Stocata in Cloudinary in productie.', storage=leaves.models._signature_storage, upload_to='leaves/signatures/', verbose_name='Imagine semnatura'),
        ),
    ]
